### ISSUE TITLE
Webcam/audio prompts don't appear

### ISSUE THREAD

**Issue by therobinkim** [realFacesTeam/Real-Faces#217]
I think this error message in the browser's console may be related:

getUserMedia() no longer works on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.

**Comment by davemun** [comment]
Hello Robin,

As I now work for a webRTC company, I can very assuredly tell you this is because user camera/mic access is now blocked on non-HTTPS sites on Chrome 47+ for security reasons.

I will patch it to serve via HTTPS, but you can use it in Firefox in the meantime and it should be fine.

**Comment by therobinkim** [comment]
COOL good to know! :dancers:

**Comment by davemun** [comment]
Rory patched it by changing the realfaces.org domain to redirect directly to the Heroku instance instead of having to buy our own SSL cert - it works again.
